# -*- mode: ruby -*-
# vi: set ft=ruby :

mod 'puppetlabs/stdlib', '3.2.2'
mod 'puppetlabs/concat', '1.2.5'
mod 'puppetlabs/inifile', '1.4.3'
mod 'saz/ssh', '2.8.1'
mod 'saz/timezone', '3.3.0'

mod 'zack/r10k',
  :git => 'https://github.com/acidprime/r10k',
  :tag => 'v3.1.1'

mod 'nexcess/ksplice',
  :git => 'https://github.com/nexcess/puppet-ksplice.git',
  :tag => 'v2.0.0'   
